# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAgregarproductos():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_agregarproductos(self):
    self.driver.get("http://127.0.0.1:8000/")
    self.driver.set_window_size(1440, 774)
    self.driver.find_element(By.CSS_SELECTOR, ".s-3").click()
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(6)").click()
    self.driver.find_element(By.NAME, "username").click()
    self.driver.find_element(By.NAME, "username").send_keys("Camila")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("pelicanoprueba1")
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex > button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bi").click()
    self.driver.find_element(By.LINK_TEXT, "Limpiar").click()
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".overlay-content > a:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".box:nth-child(2) a").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "h5:nth-child(2)").text == "1"
    self.driver.find_element(By.LINK_TEXT, "Añadir al carrito").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "h5:nth-child(2)").text == "2"
    self.driver.find_element(By.CSS_SELECTOR, ".box:nth-child(3) a").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "h5:nth-child(2)").text == "3"
    self.driver.find_element(By.CSS_SELECTOR, ".box:nth-child(2) a").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "h5:nth-child(2)").text == "4"
    self.driver.find_element(By.CSS_SELECTOR, ".s-2").click()
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(5)").click()
  
