# Generated by Django 4.0.4 on 2022-06-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_remove_cliente_seriecliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='serieCliente',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
